Scraping from website
chihacknight/energy-news-roundup pull request #1
Opened 2022-06-26 04:38 UTC by SuragNuthulapaty

Added scraping of category, date, publication, blurb, all links in the blurb, and the article link for both bullet-pointed categories and non-bullet-pointed categories. Also added pandas and openpyxl for putting the data into a spreadsheet.

2022-06-28 19:55 UTC, derekeder commented
@SuragNuthulapaty looking good! did you want a review of this pull request or should we review it together tonight?

2022-06-28 21:17 UTC, SuragNuthulapaty commented
I was thinking we would review it later tonight

2022-06-29 00:03 UTC, herrerarobert commented
The data in the spreadsheet seems good to me. One small comment: is there a built-in python lib we could use instead of importing pandas?

2022-06-30 03:05 UTC, SuragNuthulapaty commented
@derekeder i just committed what we were working on yesterday if you want to take a look at it

2022-07-03 19:15 UTC, derekeder requested changes
@SuragNuthulapaty looking good! I made a few comments regarding commented lines and unused imports.

I also agree with @herrerarobert that we shouldn't need to import the entire `pandas` library to export to a spreadsheet. Its a pretty heavy library. For simplicity and also better compatibility, we should export as a `csv` file using the standard csv library.

We should write the csv using `csv.DictWriter` that will write our existing `digestItems` data to a csv file. Here's an example of how to do that: https://docs.python.org/3/library/csv.html#csv.DictWriter

Finally, we should include documentation in the Pull Request and also in the README on how to run the script and what the expected output should be. Also, any notes on how common parameters to change, how long it takes to run, etc. 

Here's an example of a pull request format you can follow: https://github.com/chihacknight/decarbonize-my-state/pull/85

2022-07-03 19:15 UTC, derekeder commented on scrape.py
> +from typing import final
looks like these top 3 imports are unused. lets remove them

2022-07-03 19:15 UTC, derekeder commented on scrape.py
>  import time					   #Importing the time library
also unused

2022-07-03 19:15 UTC, derekeder commented on scrape.py
> +from zmq import curve_public
also unused

2022-07-03 19:15 UTC, derekeder commented on scrape.py
> +            # print(p.find('strong'))
we should remove commented out print statements like these

2022-07-03 19:15 UTC, derekeder commented on scrape.py
> +
extra newlines here are unneeded

2022-07-03 19:15 UTC, derekeder commented on scrape.py
>          #TODO should get Category, date, publication, blurb, link to the page, plus all links within the blurb, city, state
this TODO is done, right? if so lets remove it

2022-07-03 19:15 UTC, derekeder commented on scrape.py
> +    # soup = BeautifulSoup(parsedText, 'lxml')
remove commented line

2022-07-03 19:15 UTC, derekeder commented on scrape.py
>  # TODO store in a structured way.
remove this TODO

2022-07-06 02:15 UTC, derekeder approved these changes
@SuragNuthulapaty this looks good! We can merge this in.

The next step is to review the output data and see if there's any changes to make to massage the data. I created a Google Sheet of the scraped digest items here as well as a summary table for counts of each category: https://docs.google.com/spreadsheets/d/1n_ruhDMz0g-b2yfhak1m9fq7Xr_0SY5rqPeamJqPHho/edit#gid=1843617235

From this, it looks like there are a few redundant / inconsistently named categories we're pulling like `OIL AND GAS` vs `OIL & GAS` etc: https://docs.google.com/spreadsheets/d/1n_ruhDMz0g-b2yfhak1m9fq7Xr_0SY5rqPeamJqPHho/edit#gid=934319479

We should try to clean up / merge these together. A few ideas for that:
- convert all text to uppercase and strip out all non-letter characters
- create a list of categories to ignore, like `YOUR AD HERE` and `YOUR MESSAGE HERE`
- for the `ALSO` and `MEANWHILE` articles, maybe associate them with the previously found category?

2022-07-06 04:52 UTC, merged