Put states to entries
chihacknight/energy-news-roundup pull request #5
Opened 2022-08-24 23:17 UTC by SuragNuthulapaty

# Overview

Fixes #3 

Gets a state and/or city related to each blurb and adds it as a new column in the table.

# Notes

Not all rows have a location attached to it due to how the library works. We might need to go in manually and fix up everything else.

2022-08-25 21:16 UTC, derekeder requested changes
@SuragNuthulapaty Looking good. I have one comment on formatting and some notes on the accuracy and ways to improve our coverage.

I put all the latest data into a new sheet and did a summary pivot table: https://docs.google.com/spreadsheets/d/1SZ1NrJgAnjUwHo_ZVv-TwRrb1-wdb64wVLcIkMI_XiU/edit#gid=1630528016

A few observations for the [State classifications](https://docs.google.com/spreadsheets/d/1SZ1NrJgAnjUwHo_ZVv-TwRrb1-wdb64wVLcIkMI_XiU/edit#gid=1525064602):
* 35,500 / 90,993 have no state assigned (61% coverage)
* it does seem to be missing some obvious ones like `Hawaii’s only coal plant is on track to shut down by Sept. 1 ...` and `The ongoing drought in the Colorado River Basin ...`. I wonder if accuracy would improve if we didn't concatenate the link and just went with blurb & publication.
* some of the state classifications are inaccurate (seeing `North`, `West` and `Paris` as values). we should run the found states through a known list of valid states and filter out the incorrect ones
* many entries have more than one state assigned, which is ok

A few observations for the [City classifications](https://docs.google.com/spreadsheets/d/1SZ1NrJgAnjUwHo_ZVv-TwRrb1-wdb64wVLcIkMI_XiU/edit#gid=935733072):
* 39,076 / 90,993 have no city assigned (57% coverage)
* City classification is much less accurate. Seeing State names and other words like `Hill` `Energy` and `House`. This is harder to clean up as it would require a list of all possible cities in the US.

2022-08-25 21:16 UTC, derekeder commented on scrape.py
> +    curItem['cities'] = getStates(curItem).cities
the array brackets `[` make this a little harder to work with in the spreadsheet. lets convert them into a string with a comma separated list. 

We can do something like this:
`curItem['states'] = ",".join(str(x) for x in curItem['states'])`

Lets do this for, `cities`, `regions` and `links-within-blurb`

2022-09-21 16:02 UTC, derekeder commented
@SuragNuthulapaty pulled in the latest scrape from yesterday.

Looks like we successfully removed most of the false positives. However, our overall tagging coverage went down:

38,759 / 93,489 untagged = 58.5% coverage

I think this is good to bring in. We can work on improving the accuracy in a future PR

2022-09-21 21:41 UTC, SuragNuthulapaty commented
@derekeder I just pushed up the newest run, it should be up to date now

2022-09-21 21:53 UTC, derekeder approved these changes
@SuragNuthulapaty cool. looks like the digestItems didn't change from the one I used earlier. this looks good to bring in!

2022-09-21 21:54 UTC, merged